### ISSUE TITLE
Hosted version of site is down

### ISSUE THREAD

**Issue by rpodcast** [phdjsep/quarto-club#13]
I wanted to show off the site to a colleague and it looks like the hosted version of the site is down. Are you planning to keep maintaining the site?

**Comment by phdjsep** [comment]
Hi Eric,

Thanks for the message. Posit told me I couldn't continue using the quarto name in the domain, so the site can now be found at https://qmdclub.com/

I'll need to socialize that a bit more.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by rpodcast** [comment]
Updating my existing bookmark! Thank you so much for keeping this terrific site going.
